name: Sync tutorial

on:
  repository_dispatch:
    types:
      - trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: |
          echo "Workflow triggered"
